version: "3.2"
volumes:
  weather:
    external: true
services:
  # network_mode: host
  consumer:
    build: ./Consumer
    container_name: consumer
    # network_mode: host
    ports: 
      - "5000:5000"
    volumes:
      - weather:/app/data

  pub:
    build: ./Publisher_Module
    container_name: pub
    # network_mode: host
    ports: 
      - "5001:5000"
  sub:
    build: ./Subscriber_Module
    container_name: sub
    # network_mode: host
    ports: 
      - "5002:5000"
  producer:
    build: ./Producer
    container_name: producer
    # network_mode: host
    ports: 
      - "5003:5000"
    volumes:
      - weather:/app/data
  # broker3:
  #   build: ./Broker_3
  #   container_name: broker3
  #   # network_mode: host
  #   ports: 
  #     - "5004:5000"
  #   volumes:
  #     - weather:/app/data

  # https://github.com/wurstmeister/zookeeper-docker
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - "2181:2181"

  # https://hub.docker.com/r/confluentinc/cp-kafka/
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.2.1

    ports:
    - 9092:9092

    depends_on:
    - zookeeper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ## the >- used below infers a value which is a string and properly 
      ## ignore the multiple lines resulting in one long string: 
      ## https://yaml.org/spec/1.2/spec.html
      KAFKA_ADVERTISED_LISTENERS: >- 
        LISTENER_DOCKER_INTERNAL://kafka:19092, 
        LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-kafka}:9092,
        LISTENER_DOCKER_kafka2://${DOCKER_HOST_IP:-kafka2}:9091,
        LISTENER_DOCKER_kafka3://${DOCKER_HOST_IP:-kafka3}:9090

      KAFKA_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://:19092,
        LISTENER_DOCKER_EXTERNAL://:9092,
        LISTENER_DOCKER_kafka2://:9091,
        LISTENER_DOCKER_kafka3://:9090


      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >- 
        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL:PLAINTEXT,
        LISTENER_DOCKER_kafka2:PLAINTEXT,
        LISTENER_DOCKER_kafka3:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_LOG4J_LOGGERS: >- 
        kafka.controller=INFO,
        kafka.producer.async.DefaultEventHandler=INFO,
        state.change.logger=INFO
        
  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:2.12-2.2.1

    ports:
    - 9091:9091

    depends_on:
    - zookeeper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ## the >- used below infers a value which is a string and properly 
      ## ignore the multiple lines resulting in one long string: 
      ## https://yaml.org/spec/1.2/spec.html
      KAFKA_ADVERTISED_LISTENERS: >- 
        LISTENER_DOCKER_INTERNAL://kafka:19091, 
        LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-kafka2}:9091,
        LISTENER_DOCKER_kafka1://${DOCKER_HOST_IP:-kafka}:9092,
        LISTENER_DOCKER_kafka3://${DOCKER_HOST_IP:-kafka3}:9090

      KAFKA_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://:19091,
        LISTENER_DOCKER_EXTERNAL://:9091,
        LISTENER_DOCKER_kafka1://:9092,
        LISTENER_DOCKER_kafka3://:9090
      

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >- 
        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL:PLAINTEXT,
        LISTENER_DOCKER_kafka1:PLAINTEXT,
        LISTENER_DOCKER_kafka3:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_LOG4J_LOGGERS: >- 
        kafka.controller=INFO,
        kafka.producer.async.DefaultEventHandler=INFO,
        state.change.logger=INFO


  kafka3:
    container_name: kafka3
    image: wurstmeister/kafka:2.12-2.2.1

    ports:
    - 9090:9090

    depends_on:
    - zookeeper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ## the >- used below infers a value which is a string and properly 
      ## ignore the multiple lines resulting in one long string: 
      ## https://yaml.org/spec/1.2/spec.html
      KAFKA_ADVERTISED_LISTENERS: >- 
        LISTENER_DOCKER_INTERNAL://kafka:19090, 
        LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-kafka2}:9090,
        LISTENER_DOCKER_kafka1://${DOCKER_HOST_IP:-kafka}:9092,
        LISTENER_DOCKER_kafka2://${DOCKER_HOST_IP:-kafka3}:9091

      KAFKA_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://:19090,
        LISTENER_DOCKER_EXTERNAL://:9090,
        LISTENER_DOCKER_kafka1://:9092,
        LISTENER_DOCKER_kafka2://:9091

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >- 
        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL:PLAINTEXT,
        LISTENER_DOCKER_kafka1:PLAINTEXT,
        LISTENER_DOCKER_kafka2:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 4
      KAFKA_LOG4J_LOGGERS: >- 
        kafka.controller=INFO,
        kafka.producer.async.DefaultEventHandler=INFO,
        state.change.logger=INFO





