DROP TABLE IF EXISTS climate;

CREATE TABLE climate (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    request_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    from_year INTEGER NOT NULL,
    to_year INTEGER NOT NULL,
    type TEXT NOT NULL,
    var TEXT NOT NULL,
    ISO3 TEXT NOT NULL,
    ext TEXT NOT NULL
);