DROP TABLE IF EXISTS climate;

CREATE TABLE climate (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    request_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ISO3 TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    PHEN TEXT NOT NULL
);