DROP TABLE IF EXISTS climate;

CREATE TABLE climate (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    request_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PERIOD TEXT NOT NULL,
    PHEN TEXT NOT NULL
);